# Generated by Django 5.0.1 on 2024-02-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_AddedBudgetTable'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=10),
            preserve_default=False,
        ),
    ]
